services:
  # --- BASE DE DATOS 1: GESTIÓN DE PEDIDOS ---
  bd-pedidos:
    image: postgres:15-alpine
    container_name: g5-bd-pedidos
    command: postgres -c logging_collector=on -c log_destination=stderr
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_USER: user_pedidos
      POSTGRES_PASSWORD: password_pedidos
    volumes:
      - vol_pedidos_data:/var/lib/postgresql/data
      - ./init-pedidos.sql:/docker-entrypoint-initdb.d/init-pedidos.sql
    ports:
      - "5431:5432"
    networks:
      - red-insumos-medicos

  # --- BASE DE DATOS 2: INVENTARIO DE BODEGA ---
  bd-inventario:
    image: postgres:15-alpine
    container_name: g5-bd-inventario
    command: postgres -c logging_collector=on -c log_destination=stderr
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: user_inventario
      POSTGRES_PASSWORD: password_inventario
    volumes:
      - vol_inventario_data:/var/lib/postgresql/data
      - ./init-inventario.sql:/docker-entrypoint-initdb.d/init-inventario.sql
    ports:
      - "5432:5432"
    networks:
      - red-insumos-medicos

  # --- BASE DE DATOS 3: CONTABILIDAD MÉDICA ---
  bd-contabilidad:
    image: postgres:15-alpine
    container_name: g5-bd-contabilidad
    command: postgres -c logging_collector=on -c log_destination=stderr
    environment:
      POSTGRES_DB: contabilidad_db
      POSTGRES_USER: user_contabilidad
      POSTGRES_PASSWORD: password_contabilidad
    volumes:
      - vol_contabilidad_data:/var/lib/postgresql/data
      - ./init-contabilidad.sql:/docker-entrypoint-initdb.d/init-contabilidad.sql
    ports:
      - "5433:5432"
    networks:
      - red-insumos-medicos

  # --- RESPALDOS AUTOMÁTICOS CADA 10 MINUTOS ---
  respaldos-automaticos:
    image: prodrigestivill/postgres-backup-local:15-alpine
    container_name: g5-respaldos
    restart: always
    volumes:
      - ./backups:/backups
    environment:
      - POSTGRES_HOST=bd-pedidos,bd-inventario,bd-contabilidad
      - POSTGRES_USER=user_pedidos,user_inventario,user_contabilidad
      - POSTGRES_PASSWORD=password_pedidos,password_inventario,password_contabilidad
      - POSTGRES_DB=pedidos_db,inventario_db,contabilidad_db
      - SCHEDULE=@every 10m
      - BACKUP_KEEP_MINS=60
    networks:
      - red-insumos-medicos

  # --- HERRAMIENTA VISUAL: PGADMIN 4 ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: g5-pgadmin
    environment:
      PGADMIN_SETUP_EMAIL: admin@grupo5.cl
      PGADMIN_SETUP_PASSWORD: adminpassword
      PGADMIN_DEFAULT_EMAIL: admin@grupo5.cl
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    networks:
      - red-insumos-medicos
    depends_on:
      - bd-pedidos
      - bd-inventario
      - bd-contabilidad

# --- DECLARACIÓN DE VOLÚMENES (PERSISTENCIA) ---
volumes:
  vol_pedidos_data:
  vol_inventario_data:
  vol_contabilidad_data:

# --- RED INTERNA ---
networks:
  red-insumos-medicos:
    driver: bridge